config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users
  root to: "home#index"
  # get "articles/user/:user_id",to: "articles#from_author"

   resources :articles do
     get "user/:user_id",to: "articles#from_author",on: :collection
   end


   # get "articles/index",to: "articles#index"
   # get "articles/new", to: "articles#new", as: :new_article
   # post "articles", to: "articles#create"
   # get "articles/:id", to: "articles#show"
   # get "articles/:id/edit", to: "articles#edit", as: :edit_article
   # patch "/articles/:id",to: "articles#update", as: :article
   # delete "articles/:id", to: "articles#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :rayContent
  belongs_to :user
  has_many :has_categories
  has_many :categories,through: :has_categories
  attr_accessor :category_elements

  def save_categories
    return has_categories.destroy_all if category_elements.nil? || category_elements.empty?

    has_categories.where.not(category_id: category_elements).destroy_all

    category_elements.each do |category_id|
      HasCategory.find_or_create_by(article: self,category_id: category_id)
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :has_categories

  has_many :articles,through: :has_categories
end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/Base_controller.rb
class BaseController < ApplicationController

  before_action :authenticate_user!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < BaseController
  before_action :find_article, only: [:edit,:show,:update,:destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def from_author
    @user =  User.find(params[:user_id])
  end

  def new
    @article = Article.new
    @categories = Category.all
    #@article.title = "Mostrando algo"
    #@article.rayContent = "pa que salga algo"
  end

  def create

    @article = Article.create(title: params[:article][:title], category_elements: params[:article][:category_elements],
                              rayContent: params[:article][:rayContent], user: current_user)
    # render json: @article
    @article.save_categories
    redirect_to articles_path
  end
  def edit
    @categories = Category.all
  end

  def update
    #@article = Article.find(params[:id])
    @article.update(title: params[:article][:title], category_elements: params[:article][:category_elements],rayContent: params[:article][:rayContent],user: current_user)

    @article.save_categories
    redirect_to @article
  end

  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end
  def find_article
    @article = Article.find(params[:id])
  end

  def strong_params
    params.require(:article).permit(:title,:rayContent,:user_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < BaseController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :color)
    end
end

app/controllers/home_controller.rb
class HomeController < BaseController

  # before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="card padding margin-top">

  <h4 class="text-uppercase"><%= article.title %></h4>
  <p class="text-secondary"><%=article.created_at %></p>
  <%= link_to "Ver mas", article %>
  <%#= link_to "Editar", controller:"articles",action:"edit", id: article%>
  <%= link_to "Editar", edit_article_path(id: article)%>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form|%>
  <div class="field">
    <%=form.label :title %>
    <%=form.text_field :title %>
  </div>

  <div class="field">
    <%=form.label :category_elements %>
    <div class="row">
      <% @categories.each do |category|%>
        <label class="col-6 col-sm-4">
          <%= form.check_box :category_elements,{ multiple: true },category.id, nil %>
          <%= category.title %>
        </label>
      <% end %>
    </div>
  </div>


  <div class="field">
    <%=form.label :rayContent %>
    <%=form.rich_text_area :rayContent %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<%end%>

app/views/articles/edit.html.erb
<div class="small-container center-block">

  <%= render "articles/form" %>
</div>

app/views/articles/from_author.html.erb
<div class="large-container center-block">

  <h1> Articulos del autor <%= @user.email %></h1>

  <%= render @user.articles %>
</div>

app/views/articles/index.html.erb
<div class="large-container center-block">

  <h1> Lista de articulos</h1>

  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<div class="small-container center-block">

  <%= render "articles/form" %>
</div>

app/views/articles/show.html.erb
<div>
  <h1><%=@article.title %></h1>
</div>

<div>
  <h4>
    <%=@article.rayContent %>
  </h4>
</div>

<div class="margin-top">
  <p class="label">
    Categories
  </p>
  <% @article.categories.each do |category|%>
  <span class="badge badge-pill padding" style="background-color: <%=category.color %>">
    <%= link_to category.title, category, class: "text-white" %>
  </span>
  <% end %>
</div>

<div>
  <%=link_to "Eliminar articulo",@article, method: :delete %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.color_field :color %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar",class:"btn btn-primary"%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="small-container center-block">
  <h1>Editing Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Show', @category %> |
  <%= link_to 'Back', categories_path %>

</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div class="small-container center-block">

  <h1>New Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>

</div>

app/views/categories/show.html.erb
<div class="large-container center-block">

  <h1> Titulo de la categoria: <%= @category.title %></h1>

  <%= render @category.articles %>
</div>


<!--<p id="notice"><%#= notice %></p>-->

<!--<p>-->
<!--  <strong>Title:</strong>-->
  <%#= @category.title %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Color:</strong>-->
  <%#= @category.color %>
<!--</p>-->

<!--<%#= link_to 'Edit', edit_category_path(@category) %> |-->
<%#= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<%if user_signed_in? %>
  <h1>Hey, Hola <%= current_user.email%></h1>

  <% else %>

  <h1>Hey, Hola Mundo! Autentiquese</h1>
  <%end %>


<%= link_to "Inicio", articles_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>

    <p class="alert alert-primary"><%= notice %></p>
  <% end %>

  <% if alert %>

    <p class="alert alert-danger"><%= alert %></p>
  <%end %>

  <%= render "partials/nav" %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="nav bg-light padding">
  <li class="nav-item">
    <%= link_to "Inicio", root_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Articulos", articles_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Nuevo articulo", new_article_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Categorias", categories_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Nueva Categoria", new_category_path, class: "nav-link" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to "Iniciar sesion", new_user_session_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Registrar", new_user_registration_path, class: "nav-link" %>
    </li>
  <%end %>


</nav>